
require:
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
